=== androids7/swingme/SwingME/resources/SynthME.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!--
 @(#)SynthME.dtd 1.0

 This file is part of 'yura.net Swing ME'.

 'yura.net Swing ME' is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 'yura.net Swing ME' is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with 'yura.net Swing ME'. If not, see <http://www.gnu.org/licenses/>.
-->

<!--
removed:  font | color | imagePainter | imageIcon | inputMap
-->
    <!ELEMENT synth (style | bind)*>
    <!ATTLIST synth
          version              CDATA          #IMPLIED
    >

<!--
removed:  property | defaultsProperty | font | graphicsUtils | painter | imagePainter | opaque | inputMap
-->
    <!ELEMENT style ( state | insets | imageIcon)*>
    <!ATTLIST style
          id                   ID             #IMPLIED
          clone                IDREF          #IMPLIED
    >

<!--
added: property, it should be there, DTD was wrong
removed: painter
value can be:
 ENABLED
 DISABLED
 FOCUSED
 SELECTED
Multiple states should be separated by 'AND'.
If you do not specify a value, the contents apply to all states. 
-->
    <!ELEMENT state (font | color | imagePainter | property)*>
    <!ATTLIST state
          id                   ID             #IMPLIED
          clone                IDREF          #IMPLIED
          value                CDATA          #IMPLIED
          idref                IDREF          #IMPLIED
    >

<!--
face - one of SYSTEM, MONOSPACE, or PROPORTIONAL
style - PLAIN, or a combination of BOLD, ITALIC, and UNDERLINED
size - one of SMALL, MEDIUM, or LARGE 
-->
    <!ELEMENT font EMPTY>
    <!ATTLIST font
          id                   ID             #IMPLIED
          idref                IDREF          #IMPLIED
          name                 CDATA          #IMPLIED
          style                CDATA          #IMPLIED
          size                 CDATA          #IMPLIED
    >

<!--
"name" renamed to "type" because DTD was wrong
type can be:
FOREGROUND
BACKGROUNG
BORDERFILL
-->
    <!ELEMENT color EMPTY>
    <!ATTLIST color
          id                   ID             #IMPLIED
          idref                IDREF          #IMPLIED
          type                 CDATA          #IMPLIED
          value                CDATA          #IMPLIED
    >

<!--
key can be:
 icon
for 
 CheckBox
 RadioButton
 ComboBox
 TitleBar
also
 Spinner.icon.disabled.right
 Spinner.icon.disabled.left
 Spinner.icon.enabled.right
 Spinner.icon.enabled.left
 Spinner.icon.pressed.right
 Spinner.icon.pressed.left
TODO: ScrollBar Skin
-->
    <!ELEMENT property EMPTY>
    <!ATTLIST property
          key         CDATA                                           #REQUIRED
          type        (idref|boolean|dimension|insets|integer)        "idref"
          value       CDATA                                           #REQUIRED
    >

    <!ELEMENT insets EMPTY>
    <!ATTLIST insets
          id                   ID             #IMPLIED
          idref                IDREF          #IMPLIED
          top                  CDATA          #IMPLIED
          bottom               CDATA          #IMPLIED
          left                 CDATA          #IMPLIED
          right                CDATA          #IMPLIED
    >

<!--
removed: type (NAME|REGION) "REGION"
key can be:
 Button
 CheckBox
 ComboBox
 Component
 Label
 List
 Menu
 Panel
 ProgressBar
 RadioButton
 ScrollPane
 Spinner
 SpriteLabel
 TabbedPane
 Table
 TextArea
 TextField
 TitleBar
 Window
-->
    <!ELEMENT bind EMPTY>
    <!ATTLIST bind
          style                IDREF          #REQUIRED
          key                  CDATA          #REQUIRED
    >


<!--
sourceInsets="top left bottom right"
stretch is not used on java
-->
    <!ELEMENT imagePainter EMPTY>
    <!ATTLIST imagePainter
          id                   ID             #IMPLIED
          method               CDATA          #IMPLIED
          direction            (north|south|east|west|horizontal|vertical|horizontal_split|vertical_split)          #IMPLIED
          path                 CDATA          #IMPLIED
          sourceInsets         CDATA          #IMPLIED
          destinationInsets    CDATA          #IMPLIED
          paintCenter          (true|false)   "true"
          stretch              (true|false)   "true"
    >

<!--
SwingME extra x,y,width,height
-->
    <!ELEMENT imageIcon EMPTY>
    <!ATTLIST imageIcon
          id                   ID             #REQUIRED
          path                 CDATA          #REQUIRED
	  x		       CDATA	      #IMPLIED
	  y		       CDATA	      #IMPLIED
	  width		       CDATA	      #IMPLIED
	  height	       CDATA	      #IMPLIED
    >






<!--
NOT USED:

    <!ELEMENT defaultsProperty EMPTY>
    <!ATTLIST defaultsProperty
          key         CDATA                                           #REQUIRED
          type        (idref|boolean|dimension|insets|integer)        "idref"
          value       CDATA                                           #REQUIRED
    >


    <!ELEMENT graphicsUtils EMPTY>
    <!ATTLIST graphicsUtils
          idref                IDREF          #REQUIRED
    >

    <!ELEMENT painter EMPTY>
    <!ATTLIST painter
          idref                IDREF          #IMPLIED
          method               CDATA          #IMPLIED
          direction            (north|south|east|west|horizontal|vertical|horizontal_split|vertical_split)          #IMPLIED
    >


    <!ELEMENT opaque EMPTY>
    <!ATTLIST opaque
          value                (true|false)   "true"
    >

    <!ELEMENT inputMap (bindKey)*>
    <!ATTLIST inputMap
          id                   ID             #REQUIRED
    >

    <!ELEMENT bindKey EMPTY>
    <!ATTLIST bindKey
          key                  CDATA          #REQUIRED
          action               CDATA          #REQUIRED
    >
-->

=== androids7/swingme/SwingME/resources/synthDemo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE synth SYSTEM "SynthME.dtd">
<synth>

    <style id="backingStyle">
	<state>
	    <font name="Dialog" size="14"/>
	    <color value="#D8D987" type="BACKGROUND"/>
	    <color value="#FF0000" type="FOREGROUND"/>
	</state>
    </style>
    <bind style="backingStyle" key=".*"/>


    <style id="textfield">
	<insets top="4" left="6" bottom="4" right="6"/>
	<state>
	    <font name="Verdana" size="14"/>
	    <color value="#D2DFF2" type="BACKGROUND"/>       
	    <color value="#000000" type="FOREGROUND"/>
	<imagePainter path="/textfield.png" sourceInsets="4 6 4 6" paintCenter="false"/>
	</state>
    </style>
    <bind style="textfield" key="TextField"/>


    <style id="button">
	<insets top="5" left="10" bottom="5" right="10"/>
	<opaque value="false"/>
	<state>
	<property key="Button.textShiftOffset" type="integer" value="1"/>
	    <imagePainter method="buttonBackground" path="/button.png" sourceInsets="12 15 12 15" />
	    <color type="BORDERFILL" value="#296ED3"/>
	    <font name="Dialog" size="16"/>
	    <color type="FOREGROUND" value="#FFFFFF"/>
	</state>
	<state value="FOCUSED">
	    <imagePainter path="/button_over.png" sourceInsets="12 15 12 15" />
	    <color type="BORDERFILL" value="#F37529"/>
	</state>
	<!-- not supported yet
        <state value="PRESSED"> 
	    <imagePainter path="/button_press.png" sourceInsets="12 15 12 15" />
	</state>
        -->
    </style>
    <bind style="button" key="Button"/>


    <style id="checkbox">
	<imageIcon id="check_off" path="/checkbox_off.png"/>
	<imageIcon id="check_on" path="/checkbox_on.png"/>
	<state>
	    <property key="CheckBox.icon" value="check_off"/>
	</state>
	<state value="SELECTED">
	    <property key="CheckBox.icon" value="check_on"/>
	</state>
    </style>
    <bind style="checkbox" key="CheckBox"/>
  

    <style id="scrollpane">
	<state>
	    <property key="scrollBarCol" type="integer" value="0x00FF0000"/>
	    <property key="scrollTrackCol" type="integer" value="0x00000000"/>
	</state>
    </style>
    <bind style="scrollpane" key="ScrollPane"/>

</synth>

=== androids7/swingme/SwingMETest/resources/iphone/synth.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE synth SYSTEM "SynthME.dtd">

<synth>

    <style id="global">
      <state>
        <font name="PROPORTIONAL" size="MEDIUM"/>

        <font path="/font/calibri.fnt">
            <fontImage path="/font/calibri.png" color="0x00000000"/>
            <fontImage path="/font/calibri.png" color="0x00FFFFFF"/>
        </font>
<!-- can not use old font format in synth files 
        <font path="/basicfont/font2-med.font"/>
-->
        <color type="FOREGROUND" value="#52425c"/>
      </state>
    </style>
    <bind style="global" key=".*"/>

    <style id="tooltip">
      <state>
        <color type="BACKGROUND" value="#FFFFFF"/>
      </state>
    </style>
    <bind style="tooltip" key="ToolTip"/>


    <style id="button">
      <insets top="3" left="3" bottom="3" right="3"/>
      <state>
        <imagePainter path="/iphone/button.png" sourceInsets="12 10 11 10" paintCenter="false"/>
        <color type="BORDERFILL" value="#d6d6d6"/>
      </state>
      <state value="FOCUSED">				<!-- top, left, bottom, right -->
        <imagePainter path="/iphone/highlight.png" sourceInsets="12 10 11 10" paintCenter="false"/>
        <color type="BORDERFILL" value="#8f9dac"/>
      </state>
    </style>
    <bind style="button" key="Button"/>


    <style id="text">
      <insets top="3" left="6" bottom="3" right="6"/>
      <state>
        <imagePainter path="/iphone/textbox2.png" sourceInsets="13 15 13 15" paintCenter="false"/>
        <color type="BORDERFILL" value="#d3dae4"/>
      </state>
      <state value="FOCUSED">				<!-- top, left, bottom, right -->
        <imagePainter path="/iphone/textbox.png" sourceInsets="13 15 13 15" paintCenter="false"/>
        <color type="BORDERFILL" value="#ffffff"/>
      </state>
    </style>
    <bind style="text" key="TextField"/>
    <bind style="text" key="TextArea"/>


<!--
    <style id="tabtop">
      <state>
        <imagePainter path="/iphone/tab_top.png" sourceInsets="0 20 5 20" paintCenter="false"/>
      </state>
    </style>
    <bind style="tabtop" key="TabTop"/>


    <style id="tabRendererTop">
      <insets top="4" left="3" bottom="4" right="3"/>
      <state>
        <imagePainter path="/iphone/Tab.png" sourceInsets="16 3 16 3" paintCenter="false"/>
        <color type="BORDERFILL" value="#4602bb"/>
      </state>
      <state value="SELECTED">
        <imagePainter path="/iphone/Focus.png" sourceInsets="16 3 16 3" paintCenter="false"/>
        <color type="BORDERFILL" value="#6c18f4"/>
      </state>
    </style>
    <bind style="tabRendererTop" key="TabRendererTop"/>


    <style id="tabContentBottom">
      <insets top="0" left="2" bottom="5" right="4"/>
      <state>
        <imagePainter path="/iphone/tab_bottom.png" sourceInsets="20 20 20 20" paintCenter="false"/>
        <color type="BORDERFILL" value="FFFFFF"/>
      </state>
    </style>
    <bind style="tabContentBottom" key="TabContentBottom"/>

    <style id="menu">
      <insets top="5" left="5" bottom="5" right="5"/>
      <state>
        <imagePainter path="/iphone/menu.png" sourceInsets="20 20 20 20" paintCenter="false"/>
        <color type="BORDERFILL" value="#FFFFFF"/>
      </state>
    </style>
    <bind style="menu" key="Menu"/>
-->

    <style id="window">
      <insets top="0" left="0" bottom="0" right="0"/>
      <state>
        <imagePainter path="/iphone/mainWindow.png" sourceInsets="44 0 44 0" paintCenter="true"/>
      </state>
    </style>
    <bind style="window" key="Frame"/>


    <style id="dialog">
      <insets top="30" left="30" bottom="30" right="30"/>
      <state>
        <imagePainter path="/iphone/dialog.png" sourceInsets="30 30 30 30" paintCenter="true"/>
      </state>
    </style>
    <bind style="dialog" key="Dialog"/>


    <style id="softkeys">
      <insets top="5" left="5" bottom="5" right="5"/>
      <imageIcon id="button_normal" path="/iphone/mainWindow.png" x="0" y="0" width="84" height="44"/>
      <imageIcon id="bottom_right" path="/iphone/mainWindow.png" x="0" y="75" width="84" height="44"/>
      <imageIcon id="bottom_left" path="/iphone/mainWindow.png" x="0" y="75" width="84" height="44"/>
      <state>
        <property key="button" value="button_normal"/>
        <property key="bottomRight" value="bottom_right"/>
        <property key="bottomLeft" value="bottom_left"/>
      </state>
    </style>
    <bind style="softkeys" key="SoftkeyRenderer"/>


    <style id="checkbox">
      <imageIcon id="check_on" path="/iphone/iconGrid.png" x="0" y="0" width="16" height="16"/>
      <imageIcon id="check_on_disabled" path="/iphone/iconGrid.png" x="0" y="16" width="16" height="16"/>
      <imageIcon id="check_off" path="/iphone/iconGrid.png" x="0" y="32" width="16" height="16"/>
      <imageIcon id="check_off_disabled" path="/iphone/iconGrid.png" x="0" y="48" width="16" height="16"/>
      <state>
        <property key="icon" value="check_off"/>
      </state>
      <state value="SELECTED">
        <property key="icon" value="check_on"/>
      </state>
      <state value="DISABLED">
        <property key="icon" value="check_off_disabled"/>
      </state>
      <state value="DISABLED AND SELECTED">
        <property key="icon" value="check_on_disabled"/>
      </state>
    </style>
    <bind style="checkbox" key="CheckBox"/>


    <style id="radioButton">
      <imageIcon id="radio_on" path="/iphone/iconGrid.png" x="0" y="64" width="16" height="16"/>
      <imageIcon id="radio_on_disabled" path="/iphone/iconGrid.png" x="0" y="80" width="16" height="16"/>
      <imageIcon id="radio_off" path="/iphone/iconGrid.png" x="0" y="96" width="16" height="16"/>
      <imageIcon id="radio_off_disabled" path="/iphone/iconGrid.png" x="0" y="112" width="16" height="16"/>
      <state>
        <property key="icon" value="radio_off"/>
      </state>
      <state value="SELECTED">
        <property key="icon" value="radio_on"/>
      </state>
      <state value="DISABLED">
        <property key="icon" value="radio_off_disabled"/>
      </state>
      <state value="DISABLED AND SELECTED">
        <property key="icon" value="radio_on_disabled"/>
      </state>
    </style>
    <bind style="radioButton" key="RadioButton"/>



    <style id="scrollpane">

      <imageIcon id="thumb_top" path="/iphone/thumb.png" x="0" y="0" width="14" height="14"/>
      <imageIcon id="thumb_fill" path="/iphone/thumb.png" x="0" y="14" width="14" height="14"/>
      <imageIcon id="thumb_bottom" path="/iphone/thumb.png" x="0" y="28" width="14" height="14"/>

      <imageIcon id="track_top" path="/iphone/track.png" x="0" y="0" width="14" height="22"/>
      <imageIcon id="track_fill" path="/iphone/track.png" x="0" y="22" width="14" height="12"/>
      <imageIcon id="track_bottom" path="/iphone/track.png" x="0" y="34" width="14" height="22"/>
<!--
      <imageIcon id="left_arrow" path="/iphone/scrollArrows.png" x="0" y="0" width="15" height="30"/>
      <imageIcon id="right_arrow" path="/iphone/scrollArrows.png" x="0" y="30" width="15" height="30"/>
-->
      <state>
        <property key="thumbTop" value="thumb_top"/>
        <property key="thumbBottom" value="thumb_bottom"/>
        <property key="thumbFill" value="thumb_fill"/>
        <property key="trackTop" value="track_top"/>
        <property key="trackBottom" value="track_bottom"/>
        <property key="trackFill" value="track_fill"/>
<!--
        <property key="rightArrow" value="right_arrow"/>
        <property key="leftArrow" value="left_arrow"/>
-->
      </state>
    </style>
    <bind style="scrollpane" key="ScrollPane"/>

    <style id="listRenderer">
      <insets top="3" left="3" bottom="3" right="3"/>
      <state>
        <imagePainter path="/iphone/select_row.png" sourceInsets="0 0 1 0" paintCenter="false"/>
        <color type="BORDERFILL" value="#FFFFFF"/>
      </state>
      <state value="SELECTED">
        <imagePainter path="/iphone/select_row.png" sourceInsets="43 0 1 0" paintCenter="false"/>
        <color type="BORDERFILL" value="#3b78e6"/>
      </state>
    </style>
    <bind style="listRenderer" key="ListRenderer"/>


    <style id="section">
      <insets top="5" left="5" bottom="5" right="5"/>
      <state>
        <imagePainter path="/iphone/section.png" sourceInsets="12 12 12 12" paintCenter="false"/>
        <color type="BORDERFILL" value="#ffffff"/>
      </state>
    </style>
    <bind style="section" key="Section"/>

</synth>

=== androids7/swingme/SwingMETest/resources/telus/synthVisto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE synth SYSTEM "SynthME.dtd">

<synth>

    <style id="global">
      <state>
        <font name="PROPORTIONAL" size="MEDIUM"/>
        <color type="FOREGROUND" value="#52425c"/>
      </state>
    </style>
    <bind style="global" key=".*"/>

    <style id="tooltip">
      <state>
        <color type="BACKGROUND" value="#FF00FF"/>
      </state>
    </style>
    <bind style="tooltip" key="ToolTip"/>

    <style id="photoButton">
      <insets top="3" left="3" bottom="3" right="3"/>
      <state value="FOCUSED">
        <imagePainter path="/telus/ContactPictureHighlight.png" sourceInsets="20 20 20 20" paintCenter="false"/>
      </state>
    </style>
    <bind style="photoButton" key="PhotoButton"/>

    <style id="button">
      <insets top="3" left="3" bottom="3" right="3"/>
      <state value="FOCUSED">				<!-- top, left, bottom, right -->
        <imagePainter path="/telus/highlight.png" sourceInsets="14 10 6 10" paintCenter="false"/>
        <color type="BORDERFILL" value="#49266c"/>
        <color type="FOREGROUND" value="#FFFFFF"/>
      </state>
      <state value="DISABLED">
        <color type="FOREGROUND" value="#AAAAAA"/>
      </state>
    </style>
    <bind style="button" key="Button"/>
    <bind style="button" key="CheckBox"/>
    <bind style="button" key="RadioButton"/>
    <bind style="button" key="TextField"/>
    <bind style="button" key="TextArea"/>

    <style id="tabtop">
      <state>
        <imagePainter path="/telus/tab_top.png" sourceInsets="0 20 5 20" paintCenter="false"/>
      </state>
    </style>
    <bind style="tabtop" key="TabTop"/>


    <style id="tabRendererTop">
      <insets top="4" left="3" bottom="4" right="3"/>
      <state>
        <imagePainter path="/telus/Tab.png" sourceInsets="16 3 16 3" paintCenter="false"/>
        <color type="BORDERFILL" value="#4602bb"/>
      </state>
      <state value="SELECTED">
        <imagePainter path="/telus/Focus.png" sourceInsets="16 3 16 3" paintCenter="false"/>
        <color type="BORDERFILL" value="#6c18f4"/>
      </state>
    </style>
    <bind style="tabRendererTop" key="TabRendererTop"/>


    <style id="tabContentBottom">
      <insets top="0" left="2" bottom="5" right="4"/>
      <state>
        <imagePainter path="/telus/tab_bottom.png" sourceInsets="20 20 20 20" paintCenter="false"/>
        <color type="BORDERFILL" value="FFFFFF"/>
      </state>
    </style>
    <bind style="tabContentBottom" key="TabContentBottom"/>


    <style id="window">
      <insets top="0" left="0" bottom="0" right="0"/>
      <state>
        <imagePainter path="/telus/mainWindow.png" sourceInsets="25 115 25 115" paintCenter="false"/>
        <color type="BORDERFILL" value="#FFFFFF"/>
      </state>
    </style>
    <bind style="window" key="Window"/>


    <style id="textWindow">
      <insets top="0" left="0" bottom="0" right="0"/>
      <state>
        <imagePainter path="/telus/mainWindow.png" sourceInsets="25 115 25 115" paintCenter="false"/>
        <color type="BORDERFILL" value="#FFFFFF"/>
      </state>
    </style>
    <bind style="textWindow" key="TextWindow"/>


    <style id="menu">
      <insets top="5" left="5" bottom="5" right="5"/>
      <state>
        <imagePainter path="/telus/menu.png" sourceInsets="20 20 20 20" paintCenter="false"/>
        <color type="BORDERFILL" value="#FFFFFF"/>
      </state>
    </style>
    <bind style="menu" key="Menu"/>
    <bind style="menu" key="Dialog"/>


    <style id="softkeys">
      <imageIcon id="button_normal" path="/telus/mainWindow.png" x="120" y="0" width="120" height="25"/>
      <imageIcon id="bottom_right" path="/telus/mainWindow.png" x="120" y="25" width="120" height="25"/>
      <imageIcon id="bottom_left" path="/telus/mainWindow.png" x="0" y="25" width="120" height="25"/>
      <state>
        <property key="button" value="button_normal"/>
        <property key="bottomRight" value="bottom_right"/>
        <property key="bottomLeft" value="bottom_left"/>
      </state>
    </style>
    <bind style="softkeys" key="SoftkeyRenderer"/>


    <style id="checkbox">
      <imageIcon id="check_on" path="/telus/iconGrid.png" x="0" y="0" width="20" height="20"/>
      <imageIcon id="check_on_disabled" path="/telus/iconGrid.png" x="0" y="20" width="20" height="20"/>
      <imageIcon id="check_off" path="/telus/iconGrid.png" x="0" y="40" width="20" height="20"/>
      <imageIcon id="check_off_disabled" path="/telus/iconGrid.png" x="0" y="60" width="20" height="20"/>
      <state>
        <property key="icon" value="check_off"/>
      </state>
      <state value="SELECTED">
        <property key="icon" value="check_on"/>
      </state>
      <state value="DISABLED">
        <property key="icon" value="check_off_disabled"/>
      </state>
      <state value="DISABLED AND SELECTED">
        <property key="icon" value="check_on_disabled"/>
      </state>
    </style>
    <bind style="checkbox" key="CheckBox"/>


    <style id="radioButton">
      <imageIcon id="radio_on" path="/telus/iconGrid.png" x="0" y="80" width="20" height="20"/>
      <imageIcon id="radio_on_disabled" path="/telus/iconGrid.png" x="0" y="100" width="20" height="20"/>
      <imageIcon id="radio_off" path="/telus/iconGrid.png" x="0" y="120" width="20" height="20"/>
      <imageIcon id="radio_off_disabled" path="/telus/iconGrid.png" x="0" y="140" width="20" height="20"/>
      <state>
        <property key="icon" value="radio_off"/>
      </state>
      <state value="SELECTED">
        <property key="icon" value="radio_on"/>
      </state>
      <state value="DISABLED">
        <property key="icon" value="radio_off_disabled"/>
      </state>
      <state value="DISABLED AND SELECTED">
        <property key="icon" value="radio_on_disabled"/>
      </state>
    </style>
    <bind style="radioButton" key="RadioButton"/>



    <style id="scrollpane">
      <imageIcon id="thumb_top" path="/telus/ScrollbarThumb.png" x="0" y="0" width="7" height="7"/>
      <imageIcon id="thumb_fill" path="/telus/ScrollbarThumb.png" x="0" y="7" width="7" height="16"/>
      <imageIcon id="thumb_bottom" path="/telus/ScrollbarThumb.png" x="0" y="23" width="7" height="7"/>

      <imageIcon id="track_top" path="/telus/ScrollbarPole.png" x="0" y="0" width="9" height="2"/>
      <imageIcon id="track_fill" path="/telus/ScrollbarPole.png" x="0" y="2" width="9" height="36"/>
      <imageIcon id="track_bottom" path="/telus/ScrollbarPole.png" x="0" y="38" width="9" height="2"/>

      <imageIcon id="left_arrow" path="/telus/scrollArrows.png" x="0" y="0" width="15" height="30"/>
      <imageIcon id="right_arrow" path="/telus/scrollArrows.png" x="0" y="30" width="15" height="30"/>
      <state>
        <property key="thumbTop" value="thumb_top"/>
        <property key="thumbBottom" value="thumb_bottom"/>
        <property key="thumbFill" value="thumb_fill"/>
        <property key="trackTop" value="track_top"/>
        <property key="trackBottom" value="track_bottom"/>
        <property key="trackFill" value="track_fill"/>
        <property key="rightArrow" value="right_arrow"/>
        <property key="leftArrow" value="left_arrow"/>
      </state>
    </style>
    <bind style="scrollpane" key="ScrollPane"/>





    <style id="listRenderer">
      <insets top="3" left="3" bottom="3" right="3"/>
      <font id="font2" name="PROPORTIONAL" size="LARGE"/>
      <font id="font3" name="PROPORTIONAL" size="SMALL"/>
      <state>
        <property key="font2" value="font2"/>
        <property key="font3" value="font3"/>
      </state>
      <state value="SELECTED">
        <imagePainter path="/telus/highlight.png" sourceInsets="14 10 6 10" paintCenter="false"/>
        <color type="BORDERFILL" value="#49266c"/>
        <color type="FOREGROUND" value="#FFFFFF"/>
      </state>
    </style>
    <bind style="listRenderer" key="ListRenderer"/>


    <!-- This is a theme for a custome component -->
    <style id="contacts">
      <font id="focused_name" name="PROPORTIONAL" size="LARGE"/>
      <font id="focused_status" name="PROPORTIONAL" size="SMALL"/>
      <font id="normal_name" name="PROPORTIONAL" size="LARGE"/>
      <font id="normal_status" name="PROPORTIONAL" size="SMALL"/>
      <state>
        <imagePainter path="/telus/rowBackground.png" sourceInsets="15 0 15 0" paintCenter="true"/>
	<color id="color_focused_name" value="#FFFFFF"/>
	<color id="color_focused_status" value="#000000"/>
	<color id="color_normal_name" value="#FFFFFF"/>
	<color id="color_normal_status" value="#000000"/>
        <property key="fontName" value="normal_name"/>
        <property key="fontStatus" value="normal_status"/>
        <property key="colorName" value="color_focused_name"/>
        <property key="colorStatus" value="color_focused_status"/>
        <property key="height" type="integer" value="42"/>
      </state>
      <state value="FOCUSED">
        <imagePainter path="/telus/highlightRowBackground.png" sourceInsets="10 10 10 10" paintCenter="true"/>
        <property key="fontName" value="focused_name"/>
        <property key="fontStatus" value="focused_status"/>
        <property key="colorName" value="color_normal_name"/>
        <property key="colorStatus" value="color_normal_status"/>
        <property key="height" type="integer" value="62"/>
      </state>
    </style>
    <bind style="contacts" key="ContactsRenderer"/>
</synth>
